### PR TITLE
Made changes to the home page

### PR DESCRIPTION
**Pull request by EBEREGIT**
@Ebereplenty from #fe_dragon_beast

### CODE REVIEW

**Comment by sainttobs** [comment]
can you attach a screenshot that shows the changes you made.

**Comment by sainttobs** [comment]
also describe what changes you made

**Comment by sainttobs** [comment]
fix merge conflicts

**Comment by EBEREGIT** [comment]
By screenshot, do you mean the initial homepage or my own homepage?

**Pull request closed without merging**
